# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: EugeneBarsky.EVBPlayer
PackageVersion: 0.2.7
InstallerType: nullsoft
Scope: user
InstallModes:
  - silent
  - silentWithProgress
UpgradeBehavior: install
ProductCode: c94747a7-5d2b-56ae-813e-98c1b40550a3
ReleaseDate: 2026-09-26
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/evb0110/evb-player/releases/download/v0.2.7/EVB-Player-0.2.7-x64-setup.exe
    InstallerSha256: 9CFC52F669F55DBA9079B4C80363821865AA44781292B321CC7DA956C7601775
ManifestType: installer
ManifestVersion: 1.12.0
